# Here you can find docs bitnami/nginx chart https://github.com/bitnami/charts/blob/main/bitnami/nginx/README.md

image:
  registry: docker.io
  repository: pandyz/to-dos-api
  tag: "latest"
  pullPolicy: Always
  debug: true

containerPorts:
  http: 80
  https: ""

replicaCount: 1

# 1000m means 100% of processor time 
# 1m means 0.1% of processor time.
# at start pod is being allocated with resources from requests, if it needs more consumption can grow until limits.
# if pod uses more resources than limits in spite of the reason kube-system will perform a forced restart
resources:
  limits:
    # there is no cpu limit to allow to use more if needed and available for a fraction of time without killing the pod 
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 80
    https: ""

ingress:
  enabled: true
  hostname: "to-dos.tourmalinecore.com"
  path: /api/to-dos-api(/|$)(.*)
  annotations:
    # redirect from http to https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /api/to-dos-api/$2
  ingressClassName: "nginx"
  tls: true

# not needed in this setup
serviceAccount:
  create: false

# not needed in this setup
networkPolicy:
  enabled: false
