# Here you can find docs bitnami/nginx chart https://github.com/bitnami/charts/blob/main/bitnami/nginx/README.md

image:
  registry: docker.io
  repository: pandyz/to-dos-api
  tag: "latest"
  pullPolicy: Always
  debug: true

containerPorts:
  http: 80
  https: ""

replicaCount: 1

# 1000m means 100% of processor time 
# 1m means 0.1% of processor time.
# at start pod is being allocated with resources from requests, if it needs more consumption can grow until limits.
# if pod uses more resources than limits in spite of the reason kube-system will perform a forced restart
resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 1m
    memory: 50Mi

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  path: /api/to-dos-api(/|$)(.*)
  annotations:
    # to do not redirect from http to https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/to-dos-api/$2
  ingressClassName: "nginx"
  tls: false

# no https
tls: 
  enabled: false

# not needed in this setup
serviceAccount:
  create: false

# not needed in this setup
networkPolicy:
  enabled: false
